version: '3.9'  # Updated to a widely supported version

services:
  nogos-servisi:
    container_name: nogos-servisi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Maps host port 8080 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__WebApiDatabase=Host=db;Port=5432;Database=cafadb;Username=cafadb_user;Password=siguranPass    
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    container_name: postgres-db2
    image: postgres:16
    environment:
      - POSTGRES_USER=cafadb_user
      - POSTGRES_PASSWORD=siguranPass
      - POSTGRES_DB=backup_test22
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
